### ISSUE TITLE
yarn create umi 出错

### ISSUE THREAD

**Issue by xjchilli** [umijs/create-umi#13]
请问一下，在windows 环境执行 yarn create umi报如下错误是怎么回事呢？

PS E:\projects\test> yarn create umi
yarn create v1.12.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "umi > react-loadable@5.5.0" has unmet peer dependency "react@*".
[4/4] Building fresh packages...
**success Installed "create-umi@0.5.4" with binaries:
      - create-umi
文件名、目录名或卷标语法不正确。
error Command failed.**
Exit code: 1
Command: D:\Programs\node_modules\global_modules\bin\create-umi
Arguments:
Directory: E:\projects\test
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by okoala** [comment]
yarn create umi <appName> 不是还要加 appName 吗

**Comment by xjchilli** [comment]
@okoala 不需要加的，跟这个没关系。加了也是同样报错。

**Comment by sorrycc** [comment]
没有把 `yarn global bin` 添加到 PATH 里？

**Comment by xjchilli** [comment]
@sorrycc 您好，是在系统PATH中，调用 umi dev等命令都没问题

**Comment by xjchilli** [comment]
已解决，修改全局 node_modules下的， create-umi.cmd,将  **@"%~dp0\C:\Users\xxxx\AppData\Local\Yarn\Data\global\node_modules\.bin\create-umi.cmd"   %***
改为 
**@"%C:\Users\xSoft\AppData\Local\Yarn\Data\global\node_modules\.bin\create-umi.cmd"   %***

**Comment by coderivy** [comment]
use npm create umi, done.
