### ISSUE TITLE
‘yarn create umi’  error 

### ISSUE THREAD

**Issue by Cloud33** [umijs/create-umi#19]
PS C:\Node\React\myapp> yarn create umi
yarn create v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "umi > react-loadable@5.5.0" has unmet peer dependency "react@*".
[4/4] Building fresh packages...

success Installed "create-umi@0.7.1" with binaries:
      - create-umi
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\bin\create-umi
Arguments:
Directory: C:\Node\React\myapp
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by sorrycc** [comment]
需要把 `yarn global bin` 的路径添加到 PATH 变量里。

**Comment by Cloud33** [comment]
添加了：
PS C:\Node\React\myapp> yarn global bin
C:\Program Files\nodejs\bin

但是还是报这个错误

PS C:\Node\React\myapp> umi -v
2.2.9

**Comment by gaohuasheng** [comment]
我也遇到同样的问题，是不是windows下有bug呢？

**Comment by imhele** [comment]
不要在有空格的目录下安装，会有很多问题，即使这次解决了以后还会遇到其他问题的，自己在磁盘根目录下新建一个 `programs` 或者其他不带空格的文件夹，更改 yarn 或 npm 全局安装目录到不带空格的目录下，建议终端内使用的所有工具都不要安装在有空格的目录。

**Comment by gaohuasheng** [comment]
更改目录后，报错变成如下，不过这个好像不是这个项目的问题。非常感谢您的回复
```
$ yarn create umi
yarn create v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-react-app@2.1.5" with binaries:
      - create-react-app
▒ļ▒▒▒▒▒Ŀ¼▒▒▒▒▒▒▒﷨▒▒▒▒ȷ▒▒
error Command failed.
Exit code: 1
Command: D:\nodejs\node_global\bin\create-react-app
Arguments: ismcloud_portal
Directory: D:\nodejsworkspace\reactspace
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```
