### ISSUE TITLE
 yarn create umi初始化项目失败

### ISSUE THREAD

**Issue by fenglu09** [umijs/create-umi#43]
使用 yarn create umi创建项目是报错
```
http://registry.npm.taobao.org/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz: Fetch succeeded for undefined. However, extracting "http://registry.npm.taobao.org/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz" resulted in hash "a6c0bbe1f38f3aa0b92238ecb6ff42c344d4135d", which did not match the requested hash "ed0a1edb87c05d4db1037c5f8f483d8a3b5f0825".
```

**Comment by sorrycc** [comment]
依赖安装问题，和 create-umi 没啥关系。

**Comment by fenglu09** [comment]
@sorrycc  请问有什么方式可以解决吗？试了好多次了，都不行。缓存也清理过了

**Comment by fenglu09** [comment]
问题解决了，通过npm create umi 可以正常使用

**Comment by sorrycc** [comment]
版本不对？Typescript 的选择是后面支持的。

**Comment by sorrycc** [comment]
这样试试，确保 create-umi 版本是新的。

```bash
$ npm i create-umi -g
$ create-umi -v
0.10.0
$ create-umi
```

**Comment by fenglu09** [comment]
按照你的流程试了，还是没有后面的选项。 
create-umi -v： 0.10.0

**Comment by sorrycc** [comment]
你选的是 app？app 才有 TypeScript 选项。

![image](https://user-images.githubusercontent.com/35128/53769180-15dac500-3f16-11e9-8168-f8a70f16ae38.png)

![image](https://user-images.githubusercontent.com/35128/53769188-1b380f80-3f16-11e9-9575-b87bdbd4ee6d.png)

**Comment by warmhug** [comment]
`npm i create-umi -g`... 这个为什么不更新到 readme 里？

**Comment by afc163** [comment]
直接用 `yarn create umi` 或者 `npx create-umi` 或者 `npm init umi` 就可以了，现在不需要安装全局工具了。
