### ISSUE TITLE
使用脚手架yarn create umi创建项目失败

### ISSUE THREAD

**Issue by xygzyf2008** [umijs/create-umi#8]
![image](https://user-images.githubusercontent.com/4231482/46004016-76064900-c0e4-11e8-8d9e-5bf8e4799cca.png)

umi -v
2.0.3

**Comment by sorrycc** [comment]
执行 `yarn global bin`，看下这个路径有没有被添加到 PATH 环境变量里。

**Comment by xygzyf2008** [comment]
加过环境变量了，也试了卸了yarn和umi再重装，还是不行。最后在虚拟机里重装了环境，再用脚手架就好了。谢谢了~
